## Data Types

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [3]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry',1,2,3])

print(arr.dtype)

<U21


In [6]:
import numpy as np

arr = np.array([1,2,3,4,8], dtype = "f")

print(arr.dtype)

float32


In [11]:
import numpy as np

arr = np.array([1,2,3,4,8], dtype = "f")
new = np.float32(arr)

print('Data type :', arr.dtype)
print("Data Type:" ,new.dtype)

print(arr)
print(new)

Data type : float32
Data Type: float32
[1. 2. 3. 4. 8.]
[1. 2. 3. 4. 8.]


In [13]:
import numpy as np

arr = np.array([1,2,3,4,8])
new = arr.astype(float)

print(arr)
print(new)

[1 2 3 4 8]
[1. 2. 3. 4. 8.]


## Arithmatic Operation

In [14]:
import numpy as np

var = np.array ([1,2,3,4])

varadd = var+3

print(varadd)

[4 5 6 7]


In [15]:
import numpy as np

var = np.array ([1,2,3,4])
var1 = np.array([1,2,3,4])

varadd = var+var1

print(varadd)

[2 4 6 8]


In [16]:
import numpy as np

var = np.array ([1,2,3,4])

varadd = var%3

print(varadd)

[1 2 0 1]


In [17]:
import numpy as np

var = np.array ([1,2,3,4])

varadd = var-3

print(varadd)

[-2 -1  0  1]


In [18]:
import numpy as np

var = np.array ([1,2,3,4])
var1 = np.array([1,2,3,4])

varadd = np.add(var1,3)

print(varadd)

[4 5 6 7]


## 2D Array

In [20]:
import numpy as np

var = np.array ([[1,2,3,4] , [1,2,3,4]])
var1 = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()

print (var1)
print()

varadd =  var+var1

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [2]:
import numpy as np

var =np.array([1,2,3,4,5,6])
print("min : ",np.min(var))
print("max : ", np.max(var))

min :  1
max :  6


In [5]:
import numpy as np

var =np.array([1,2,3,4,5,6])
print("min : ",np.min(var),np.argmin(var))
print("max : ", np.max(var),np.argmax(var))
print("sqrt : ",np.sqrt(var))

min :  1 0
max :  6 5
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [4]:
var1 = np.array([[2,1,3],[9,5,6]])

print (np.min(var1,axis=1))

[1 5]


In [8]:
var2 = np.array([2,3,4,5])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[-0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 2  5  9 14]
