# Shuffle

In [1]:
import numpy as np

var = np.array([1,2,3,4,5,6])

np.random.shuffle(var)

print(var)

[3 4 5 6 2 1]


# Unique

In [2]:
var1 = np.array([1,2,3,2,3,8,9,0,4])

x  = np.unique(var1)

print(x)

[0 1 2 3 4 8 9]


In [4]:
var1 = np.array([1,2,3,2,3,8,9,0,4])

x  = np.unique(var1, return_index = True ,return_counts = True)

print(x)

(array([0, 1, 2, 3, 4, 8, 9]), array([7, 0, 1, 2, 8, 5, 6]), array([1, 1, 2, 2, 1, 1, 1]))


In [7]:
var2 = np.array([1,2,3,4,5,6])

y =np.resize (var2,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
var2 = np.array([1,2,3,4,5,6])

y =np.resize (var2,(3,2))

print(y)
print()
print("Flatten :" ,y.flatten(order = 'F'))
print('Ravel :' ,np.ravel(y,order = 'a'))

[[1 2]
 [3 4]
 [5 6]]

Flatten : [1 3 5 2 4 6]
Ravel : [1 2 3 4 5 6]
