## Array

In [3]:
import numpy as np

x = np.array([1,2,3,4])
print (x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [7]:
l = []
for i in range (1,5):
     int_l = int(input("enter :"))
     l.append(int_l)

print(np.array(l))


enter : 2
enter : 3
enter : 36
enter : 3


[ 2  3 36  3]


## 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [10]:
import numpy as np

arr = np.array(42)

print(arr)

42


## 1-D Array

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print (arr.ndim)

[1 2 3 4 5]
1


## 2-D Arrays

In [ ]:
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


## 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [13]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## 10-D Array

In [1]:
import numpy as np
arr = np.array([1,2,3,4],ndmin = 10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Zeros

In [7]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [8]:
ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


## Empty

In [9]:
E = np.empty(4)
print(E)

[1. 1. 1. 1.]


## Range

In [11]:
Ar_R = np.arange(4)
print(Ar_R)

[0 1 2 3]


## Diagonal

In [12]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Linspace

In [16]:
ar_line = np.linspace(0,10,num=5)
print(ar_line)

[ 0.   2.5  5.   7.5 10. ]


## Random

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

## Rand()

The random module's rand() method returns a random float between 0 and 1.

In [19]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.90640932 0.12055059 0.07463787 0.0549088 ]


In [20]:
import numpy as np
var1 = np.random.rand(2,5)
print(var1)

[[0.559731   0.58805127 0.74088782 0.55276716 0.36652741]
 [0.87223087 0.13065484 0.25789314 0.11634395 0.36436147]]


## randn()

The randint() method takes a size parameter where you can specify the shape of an array.

In [22]:
import numpy as np
var2 = np.random.randn(5)
print(var2)

[ 1.30330279  0.46669668 -0.15699487 -0.0334122   0.4080192 ]


## ranf()

In [24]:
import numpy as np
var3 = np.random.ranf(5)
print(var3)

[0.6926573  0.61098119 0.8420711  0.29976308 0.13252074]


## randint()

In [25]:
import numpy as np
var4 = np.random.randint(5,20,4)
print(var4)

[ 6  6 19 12]
