In [1]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()

(3,)

[1 2 3]



In [2]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()


var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]


In [4]:
import numpy as np

var1 = np.array ([1,2,3])
print(var1.shape)
print()
print(var1)
print()


var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()
print(var1+var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
import numpy as np

var3 = np.array([[1],[2],[3]])
print(var2.shape)

var4 = np.array([])
print(var2)
print()
print(var1+var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]
