## Indexing

In [2]:
import numpy as np

var = np.array([9,8,7,6])


print(var[1])
print(var[-3])

8
8


In [4]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [9]:
var2 = np.array([[[1,2],[4,2]]])

print(var2)
print(var2.ndim)
print()

print(var2[0,1,1])

[[[1 2]
  [4 2]]]
3

2


## Slicing

In [13]:
 import numpy as np

var = np.array ([1,2,3,4,5,6,7])

print(var)
print()
print("2 to 5 : " , var [1:5])
print("2 to End : " , var[1:])
print("Start to 5 : ", var[:5])
print("Stop : " ,var[::2])

[1 2 3 4 5 6 7]

2 to 5 :  [2 3 4 5]
2 to End :  [2 3 4 5 6 7]
Start to 5 :  [1 2 3 4 5]
Stop :  [1 3 5 7]


In [17]:
var1 = np.array ([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(var1)
print()


print("8 to 5 : ", var1[1,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

8 to 5 :  [ 7  8  9 10]
