 # Insert

In [16]:
import numpy as np

x = np.array ([1,2,3,4])

print(x)

[1 2 3 4]


In [17]:
import numpy as np

x = np.array ([1,2,3,4])

print(x)

v =np.insert (x, 2 , 40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4]


In [18]:
import numpy as np

x = np.array ([1,2,3,4])

print(x)

v =np.insert (x, (2,4) , 40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [19]:
import numpy as np

x = np.array ([1,2,3,4])

print(x)

v = np.append(x,6.8)

print(v)

[1 2 3 4]
[1.  2.  3.  4.  6.8]


In [20]:
import numpy as np

x1= np.array ([[1,3,4],[1,3,4]])

v1 =np.insert (x1, 2,[22,23,24], axis = 0)

print(v1)

[[ 1  3  4]
 [ 1  3  4]
 [22 23 24]]


 # Delete

In [15]:
import numpy as np

x = np.array ([1,2,3,4])

print(x)

v = np.delete(x,2)

print(v)

[1 2 3 4]
[1 2 4]
