# Iteration

In [2]:
import numpy as np

var = np.array([9,8,7,6,5,4])

print(var)
print()
for i in var : 
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [2]:
import numpy as np
var1 = np.array([[1,2,3,4],[1,2,3,4]])

print(var1)
print()

for j in var1 : 
    print(j)

print()

for k in var1:
    for i in k:
        print(i)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [2]:
import numpy as np
var1 = np.array([[1,2,3,4],[1,2,3,4]])

print(var1)
print()

for j in var1 : 
    print(j)

print()

for k in var1:
    for i in k:
        print(i)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [7]:
import numpy as np
var2 = np.array([[[9,8,7,6],[1,2,3,4]]])

print(var2)
print(var2.ndim)
print()

for i in np.nditer(var2,flags = ['buffered'],op_dtypes = ['S']):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

np.bytes_(b'9')
np.bytes_(b'8')
np.bytes_(b'7')
np.bytes_(b'6')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [9]:
import numpy as np
var2 = np.array([[[9,8,7,6],[1,2,3,4]]])

print(var2)
print(var2.ndim)
print()

for i,d in np.ndenumerate (var2):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
