# Join

In [3]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([9,8,7,6])

ar = np.concatenate ((x,y))

print(ar)

[1 2 3 4 9 8 7 6]


In [7]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[9,8],[7,6]])

ar = np.concatenate ((x,y),axis=0)

print(x)
print()
print(y)
print()
print(ar)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [10]:
import numpy as np

x = np.array([[1,2,3,4]])
y = np.array([[9,8,7,6]])

ar = np.stack ((x,y))

print(x)
print()
print(y)
print()
print(ar)

[[1 2 3 4]]

[[9 8 7 6]]

[[[1 2 3 4]]

 [[9 8 7 6]]]


In [12]:
import numpy as np

x = np.array([[1,2,3,4]])
y = np.array([[9,8,7,6]])

ar = np.hstack ((x,y))


print(ar)

[[1 2 3 4 9 8 7 6]]


In [13]:
import numpy as np

x = np.array([[1,2,3,4]])
y = np.array([[9,8,7,6]])

ar = np.dstack ((x,y))


print(ar)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [15]:
import numpy as np

x = np.array([[1,2,3,4]])
y = np.array([[9,8,7,6]])

ar0 = np.dstack ((x,y))
ar1 = np.hstack ((x,y))  #row 
ar2 = np.vstack ((x,y)) #column
ar3 = np.dstack ((x,y))  #height


print(ar0)
print()
print(ar1)
print()
print(ar2)
print()
print(ar3)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]

[[1 2 3 4 9 8 7 6]]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split

In [19]:
import numpy as np

var = np.array ([1,2,3,4,5,6])

print (var)

ar = np.array_split(var,3)

print()
print(ar)
print(type(ar))
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [21]:
import numpy as np

var1 = np.array ([[1,2],[3,4],[5,6]])

print (var1)

ar = np.array_split(var1,3)
ar1 = np.array_split(var1,3,axis = 1)

print()
print(ar)
print()
print(ar1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
