# Search

Search array: seacrh an array for a certain value and return the indexes that get a match.

In [2]:
import numpy as np

var = np.array([1,2,3,4,5,6,3,4,8,9])

x = np.where(var == 3)

print(x)

(array([2, 6]),)


In [5]:
import numpy as np

var = np.array([1,2,3,4,5,6,3,4,8,9])

x = np.where((var%2)  == 0)

print(x)

(array([1, 3, 5, 7, 8]),)


In [6]:
import numpy as np

var1 = np.array([1,2,3,4,5,6,3,4,8,9])

x1 = np.searchsorted(var1,5)

print(x1)

4


In [12]:
import numpy as np

var1 = np.array([1,2,3,7,8,9])

x1 = np.searchsorted(var1,[4,5,8],side = 'right')

print(x1)

[3 3 5]


 # Sort

In [13]:
var2 = np.array ([4,2,3,1,12,5,6,7,3,5,7,8,9])

print(np.sort(var2))

[ 1  2  3  3  4  5  5  6  7  7  8  9 12]


In [14]:
var2 = np.array (['a','s','d','f'])

print(np.sort(var2))

['a' 'd' 'f' 's']


In [15]:
var2 = np.array ([[4,2,3,],[1,12,5],[6,7,3]])

print(np.sort(var2))

[[ 2  3  4]
 [ 1  5 12]
 [ 3  6  7]]


# Filter

In [17]:
var3 = np.array (['a','s','d','f'])

f = [True,False,False,True]

new_arr = var3 ,[f]

print(new_arr)
print(type(new_arr))

(array(['a', 's', 'd', 'f'], dtype='<U1'), [[True, False, False, True]])
<class 'tuple'>
