## Shape

In [1]:
import numpy as np

var = np.array([[2,1],[1,2]])

print(var)
print()
print(var.shape)

[[2 1]
 [1 2]]

(2, 2)


In [2]:
import numpy as np

var = np.array([2,1], ndmin = 4)

print(var)
print(var.ndim)
print()
print(var.shape)

[[[[2 1]]]]
4

(1, 1, 1, 2)


## Reshape

In [4]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [6]:
var3 = np.array([1,2,3,2,4,5,4,5,6,3,4,5])
print(var3)
print(var2.ndim)
print()
x1 = var3.reshape(2,3,2 )

print(x1)
print(x1.ndim)

[1 2 3 2 4 5 4 5 6 3 4 5]
1

[[[1 2]
  [3 2]
  [4 5]]

 [[4 5]
  [6 3]
  [4 5]]]
3


In [7]:
var3 = np.array([1,2,3,2,4,5,4,5,6,3,4,5])
print(var3)
print(var2.ndim)
print()
x1 = var3.reshape(2,3,2 )

print(x1)
print(x1.ndim)
print()

one =x1.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 2 4 5 4 5 6 3 4 5]
1

[[[1 2]
  [3 2]
  [4 5]]

 [[4 5]
  [6 3]
  [4 5]]]
3

[1 2 3 2 4 5 4 5 6 3 4 5]
1
